Structure Simulation: Stack Class Reference
Stack Class Reference
#include <stack.h>
Public Member Functions
Stack ()
~Stack ()
void clear ()
void display ()
void displayMenu ()
void handleStackOperations ()
bool isEmpty ()
int peek ()
int pop ()
void push (int x)
int size ()
int top ()
Private Attributes
int stackSize
Node * topNode
Detailed Description
Definition at line 14 of file stack.h.
Constructor & Destructor Documentation
Stack()
Stack::Stack ()
Definition at line 5 of file stack.cpp.
References stackSize, and topNode.
~Stack()
Stack::~Stack ()
Definition at line 8 of file stack.cpp.
References clear().
Member Function Documentation
clear()
void Stack::clear ()
Definition at line 59 of file stack.cpp.
References isEmpty(), stackSize, and topNode.
Referenced by ~Stack(), and handleStackOperations().
display()
void Stack::display ()
Definition at line 70 of file stack.cpp.
References Node::data, isEmpty(), Node::next, and topNode.
Referenced by handleStackOperations().
displayMenu()
void Stack::displayMenu ()
Definition at line 89 of file stack.cpp.
References CYAN, and RESET.
Referenced by handleStackOperations().
handleStackOperations()
void Stack::handleStackOperations ()
Definition at line 103 of file stack.cpp.
References clear(), cls(), CYAN, display(), displayMenu(), isEmpty(), peek(), pop(), push(), RED, RESET, and size().
Referenced by main().
isEmpty()
bool Stack::isEmpty ()
Definition at line 49 of file stack.cpp.
References topNode.
Referenced by clear(), display(), handleStackOperations(), peek(), and pop().
peek()
int Stack::peek ()
Definition at line 37 of file stack.cpp.
References isEmpty(), and topNode.
Referenced by handleStackOperations(), and top().
pop()
int Stack::pop ()
Definition at line 22 of file stack.cpp.
References isEmpty(), stackSize, and topNode.
Referenced by handleStackOperations().
push()
void Stack::push (int x)
Definition at line 13 of file stack.cpp.
References Node::next, stackSize, and topNode.
Referenced by handleStackOperations().
size()
int Stack::size ()
Definition at line 54 of file stack.cpp.
References stackSize.
Referenced by handleStackOperations().
top()
int Stack::top ()
Definition at line 44 of file stack.cpp.
References peek().
Member Data Documentation
stackSize
int Stack::stackSize private
Definition at line 17 of file stack.h.
Referenced by Stack(), clear(), pop(), push(), and size().
topNode
Node* Stack::topNode private
Definition at line 16 of file stack.h.
Referenced by Stack(), clear(), display(), isEmpty(), peek(), pop(), and push().
The documentation for this class was generated from the following files:
stack.h
stack.cpp