Structure Simulation: BinaryTree Class Reference
BinaryTree Class Reference
#include <binary_tree.h>
Public Member Functions
BinaryTree ()
~BinaryTree ()
void clear ()
void displayMenu ()
void handleBinaryTreeOperations ()
int height ()
void inOrderTraversal ()
void insert (int x)
bool isEmpty ()
int max ()
int min ()
void postOrderTraversal ()
void preOrderTraversal ()
void remove (int x)
bool search (int x)
Private Member Functions
void clearRecursive (TreeNode *node)
TreeNode * findMax (TreeNode *node)
TreeNode * findMin (TreeNode *node)
int heightRecursive (TreeNode *node)
void inOrder (TreeNode *node)
TreeNode * insertRecursive (TreeNode *node, int x)
void postOrder (TreeNode *node)
void preOrder (TreeNode *node)
TreeNode * removeRecursive (TreeNode *node, int x)
bool searchRecursive (TreeNode *node, int x)
Private Attributes
TreeNode * root
Detailed Description
Definition at line 15 of file binary_tree.h.
Constructor & Destructor Documentation
BinaryTree()
BinaryTree::BinaryTree ()
Definition at line 5 of file binary_tree.cpp.
References root.
~BinaryTree()
BinaryTree::~BinaryTree ()
Definition at line 8 of file binary_tree.cpp.
References clear().
Member Function Documentation
clear()
void BinaryTree::clear ()
Definition at line 142 of file binary_tree.cpp.
References clearRecursive(), and root.
Referenced by ~BinaryTree(), and handleBinaryTreeOperations().
clearRecursive()
void BinaryTree::clearRecursive (TreeNode * node) private
Definition at line 149 of file binary_tree.cpp.
References clearRecursive(), TreeNode::left, and TreeNode::right.
Referenced by clear(), and clearRecursive().
displayMenu()
void BinaryTree::displayMenu ()
Definition at line 181 of file binary_tree.cpp.
References CYAN, and RESET.
Referenced by handleBinaryTreeOperations().
findMax()
TreeNode * BinaryTree::findMax (TreeNode * node) private
Definition at line 175 of file binary_tree.cpp.
References TreeNode::right.
Referenced by max().
findMin()
TreeNode * BinaryTree::findMin (TreeNode * node) private
Definition at line 169 of file binary_tree.cpp.
References TreeNode::left.
Referenced by min(), and removeRecursive().
handleBinaryTreeOperations()
void BinaryTree::handleBinaryTreeOperations ()
Definition at line 199 of file binary_tree.cpp.
References clear(), cls(), CYAN, displayMenu(), height(), inOrderTraversal(), insert(), isEmpty(), max(), min(), postOrderTraversal(), preOrderTraversal(), RED, remove(), RESET, and search().
Referenced by main().
height()
int BinaryTree::height ()
Definition at line 124 of file binary_tree.cpp.
References heightRecursive(), and root.
Referenced by handleBinaryTreeOperations().
heightRecursive()
int BinaryTree::heightRecursive (TreeNode * node) private
Definition at line 129 of file binary_tree.cpp.
References heightRecursive(), TreeNode::left, and TreeNode::right.
Referenced by height(), and heightRecursive().
inOrder()
void BinaryTree::inOrder (TreeNode * node) private
Definition at line 86 of file binary_tree.cpp.
References TreeNode::data, inOrder(), TreeNode::left, and TreeNode::right.
Referenced by inOrder(), and inOrderTraversal().
inOrderTraversal()
void BinaryTree::inOrderTraversal ()
Definition at line 79 of file binary_tree.cpp.
References inOrder(), and root.
Referenced by handleBinaryTreeOperations().
insert()
void BinaryTree::insert (int x)
Definition at line 14 of file binary_tree.cpp.
References insertRecursive(), and root.
Referenced by handleBinaryTreeOperations().
insertRecursive()
TreeNode * BinaryTree::insertRecursive (TreeNode * node, int x) private
Definition at line 21 of file binary_tree.cpp.
References TreeNode::data, insertRecursive(), TreeNode::left, and TreeNode::right.
Referenced by insert(), and insertRecursive().
isEmpty()
bool BinaryTree::isEmpty ()
Definition at line 137 of file binary_tree.cpp.
References root.
Referenced by handleBinaryTreeOperations().
max()
int BinaryTree::max ()
Definition at line 163 of file binary_tree.cpp.
References TreeNode::data, findMax(), and root.
Referenced by handleBinaryTreeOperations().
min()
int BinaryTree::min ()
Definition at line 157 of file binary_tree.cpp.
References TreeNode::data, findMin(), and root.
Referenced by handleBinaryTreeOperations().
postOrder()
void BinaryTree::postOrder (TreeNode * node) private
Definition at line 116 of file binary_tree.cpp.
References TreeNode::data, TreeNode::left, postOrder(), and TreeNode::right.
Referenced by postOrder(), and postOrderTraversal().
postOrderTraversal()
void BinaryTree::postOrderTraversal ()
Definition at line 109 of file binary_tree.cpp.
References postOrder(), and root.
Referenced by handleBinaryTreeOperations().
preOrder()
void BinaryTree::preOrder (TreeNode * node) private
Definition at line 101 of file binary_tree.cpp.
References TreeNode::data, TreeNode::left, preOrder(), and TreeNode::right.
Referenced by preOrder(), and preOrderTraversal().
preOrderTraversal()
void BinaryTree::preOrderTraversal ()
Definition at line 94 of file binary_tree.cpp.
References preOrder(), and root.
Referenced by handleBinaryTreeOperations().
remove()
void BinaryTree::remove (int x)
Definition at line 30 of file binary_tree.cpp.
References removeRecursive(), and root.
Referenced by handleBinaryTreeOperations().
removeRecursive()
TreeNode * BinaryTree::removeRecursive (TreeNode * node, int x) private
Definition at line 37 of file binary_tree.cpp.
References TreeNode::data, findMin(), TreeNode::left, removeRecursive(), and TreeNode::right.
Referenced by remove(), and removeRecursive().
search()
bool BinaryTree::search (int x)
Definition at line 67 of file binary_tree.cpp.
References root, and searchRecursive().
Referenced by handleBinaryTreeOperations().
searchRecursive()
bool BinaryTree::searchRecursive (TreeNode * node, int x) private
Definition at line 72 of file binary_tree.cpp.
References TreeNode::data, TreeNode::left, TreeNode::right, and searchRecursive().
Referenced by search(), and searchRecursive().
Member Data Documentation
root
TreeNode* BinaryTree::root private
Definition at line 17 of file binary_tree.h.
Referenced by BinaryTree(), clear(), height(), inOrderTraversal(), insert(), isEmpty(), max(), min(), postOrderTraversal(), preOrderTraversal(), remove(), and search().
The documentation for this class was generated from the following files:
binary_tree.h
binary_tree.cpp