Structure Simulation: DoublyLinkedList Class Reference
DoublyLinkedList Class Reference
#include <doubly_linked_list.h>
Public Member Functions
DoublyLinkedList ()
~DoublyLinkedList ()
void clear ()
void deleteAt (int index)
void deleteFirst ()
void deleteLast ()
void display ()
void displayMenu ()
void displayReverse ()
int find (int x)
void handleDoublyLinkedListOperations ()
void insertAt (int x, int index)
void insertFirst (int x)
void insertLast (int x)
int size ()
Private Member Functions
DoublyListNode * getNodeAt (int index)
bool isValidIndex (int index)
Private Attributes
DoublyListNode * head
int listSize
DoublyListNode * tail
Detailed Description
Definition at line 15 of file doubly_linked_list.h.
Constructor & Destructor Documentation
DoublyLinkedList()
DoublyLinkedList::DoublyLinkedList ()
Definition at line 5 of file doubly_linked_list.cpp.
References head, listSize, and tail.
~DoublyLinkedList()
DoublyLinkedList::~DoublyLinkedList ()
Definition at line 8 of file doubly_linked_list.cpp.
References clear().
Member Function Documentation
clear()
void DoublyLinkedList::clear ()
Definition at line 187 of file doubly_linked_list.cpp.
References head, listSize, and tail.
Referenced by ~DoublyLinkedList(), and handleDoublyLinkedListOperations().
deleteAt()
void DoublyLinkedList::deleteAt (int index)
Definition at line 137 of file doubly_linked_list.cpp.
References DoublyListNode::data, deleteFirst(), deleteLast(), getNodeAt(), isValidIndex(), listSize, DoublyListNode::next, and DoublyListNode::prev.
Referenced by handleDoublyLinkedListOperations().
deleteFirst()
void DoublyLinkedList::deleteFirst ()
Definition at line 47 of file doubly_linked_list.cpp.
References head, listSize, and tail.
Referenced by deleteAt(), and handleDoublyLinkedListOperations().
deleteLast()
void DoublyLinkedList::deleteLast ()
Definition at line 70 of file doubly_linked_list.cpp.
References head, listSize, and tail.
Referenced by deleteAt(), and handleDoublyLinkedListOperations().
display()
void DoublyLinkedList::display ()
Definition at line 199 of file doubly_linked_list.cpp.
References DoublyListNode::data, head, and DoublyListNode::next.
Referenced by handleDoublyLinkedListOperations().
displayMenu()
void DoublyLinkedList::displayMenu ()
Definition at line 274 of file doubly_linked_list.cpp.
References CYAN, and RESET.
Referenced by handleDoublyLinkedListOperations().
displayReverse()
void DoublyLinkedList::displayReverse ()
Definition at line 221 of file doubly_linked_list.cpp.
References DoublyListNode::data, listSize, DoublyListNode::prev, and tail.
Referenced by handleDoublyLinkedListOperations().
find()
int DoublyLinkedList::find (int x)
Definition at line 166 of file doubly_linked_list.cpp.
References DoublyListNode::data, head, and DoublyListNode::next.
Referenced by handleDoublyLinkedListOperations().
getNodeAt()
DoublyListNode * DoublyLinkedList::getNodeAt (int index) private
Definition at line 243 of file doubly_linked_list.cpp.
References head, isValidIndex(), listSize, DoublyListNode::next, DoublyListNode::prev, and tail.
Referenced by deleteAt().
handleDoublyLinkedListOperations()
void DoublyLinkedList::handleDoublyLinkedListOperations ()
Definition at line 292 of file doubly_linked_list.cpp.
References clear(), cls(), CYAN, deleteAt(), deleteFirst(), deleteLast(), display(), displayMenu(), displayReverse(), find(), insertAt(), insertFirst(), insertLast(), listSize, RED, RESET, and size().
Referenced by main().
insertAt()
void DoublyLinkedList::insertAt (int x, int index)
Definition at line 93 of file doubly_linked_list.cpp.
References head, insertFirst(), insertLast(), listSize, DoublyListNode::next, DoublyListNode::prev, and tail.
Referenced by handleDoublyLinkedListOperations().
insertFirst()
void DoublyLinkedList::insertFirst (int x)
Definition at line 13 of file doubly_linked_list.cpp.
References head, listSize, DoublyListNode::next, and tail.
Referenced by handleDoublyLinkedListOperations(), and insertAt().
insertLast()
void DoublyLinkedList::insertLast (int x)
Definition at line 30 of file doubly_linked_list.cpp.
References head, listSize, DoublyListNode::prev, and tail.
Referenced by handleDoublyLinkedListOperations(), and insertAt().
isValidIndex()
bool DoublyLinkedList::isValidIndex (int index) private
Definition at line 269 of file doubly_linked_list.cpp.
References listSize.
Referenced by deleteAt(), and getNodeAt().
size()
int DoublyLinkedList::size ()
Definition at line 182 of file doubly_linked_list.cpp.
References listSize.
Referenced by handleDoublyLinkedListOperations().
Member Data Documentation
head
DoublyListNode* DoublyLinkedList::head private
Definition at line 17 of file doubly_linked_list.h.
Referenced by DoublyLinkedList(), clear(), deleteFirst(), deleteLast(), display(), find(), getNodeAt(), insertAt(), insertFirst(), and insertLast().
listSize
int DoublyLinkedList::listSize private
Definition at line 19 of file doubly_linked_list.h.
Referenced by DoublyLinkedList(), clear(), deleteAt(), deleteFirst(), deleteLast(), displayReverse(), getNodeAt(), handleDoublyLinkedListOperations(), insertAt(), insertFirst(), insertLast(), isValidIndex(), and size().
tail
DoublyListNode* DoublyLinkedList::tail private
Definition at line 18 of file doubly_linked_list.h.
Referenced by DoublyLinkedList(), clear(), deleteFirst(), deleteLast(), displayReverse(), getNodeAt(), insertAt(), insertFirst(), and insertLast().
The documentation for this class was generated from the following files:
doubly_linked_list.h
doubly_linked_list.cpp