Structure Simulation: Queue Class Reference
Queue Class Reference
#include <queue.h>
Public Member Functions
Queue ()
~Queue ()
void clear ()
int dequeue ()
void display ()
void displayMenu ()
void enqueue (int x)
int front ()
void handleQueueOperations ()
bool isEmpty ()
int size ()
Private Attributes
QueueNode * frontNode
int queueSize
QueueNode * rearNode
Detailed Description
Definition at line 14 of file queue.h.
Constructor & Destructor Documentation
Queue()
Queue::Queue ()
Definition at line 5 of file queue.cpp.
References frontNode, queueSize, and rearNode.
~Queue()
Queue::~Queue ()
Definition at line 8 of file queue.cpp.
References clear().
Member Function Documentation
clear()
void Queue::clear ()
Definition at line 67 of file queue.cpp.
References frontNode, isEmpty(), queueSize, and rearNode.
Referenced by ~Queue(), and handleQueueOperations().
dequeue()
int Queue::dequeue ()
Definition at line 28 of file queue.cpp.
References frontNode, isEmpty(), queueSize, and rearNode.
Referenced by handleQueueOperations().
display()
void Queue::display ()
Definition at line 79 of file queue.cpp.
References QueueNode::data, frontNode, isEmpty(), and QueueNode::next.
Referenced by handleQueueOperations().
displayMenu()
void Queue::displayMenu ()
Definition at line 98 of file queue.cpp.
References CYAN, and RESET.
Referenced by handleQueueOperations().
enqueue()
void Queue::enqueue (int x)
Definition at line 13 of file queue.cpp.
References frontNode, isEmpty(), queueSize, and rearNode.
Referenced by handleQueueOperations().
front()
int Queue::front ()
Definition at line 49 of file queue.cpp.
References frontNode, and isEmpty().
Referenced by handleQueueOperations().
handleQueueOperations()
void Queue::handleQueueOperations ()
Definition at line 112 of file queue.cpp.
References clear(), cls(), CYAN, dequeue(), display(), displayMenu(), enqueue(), front(), isEmpty(), RED, RESET, and size().
Referenced by main().
isEmpty()
bool Queue::isEmpty ()
Definition at line 57 of file queue.cpp.
References frontNode.
Referenced by clear(), dequeue(), display(), enqueue(), front(), and handleQueueOperations().
size()
int Queue::size ()
Definition at line 62 of file queue.cpp.
References queueSize.
Referenced by handleQueueOperations().
Member Data Documentation
frontNode
QueueNode* Queue::frontNode private
Definition at line 16 of file queue.h.
Referenced by Queue(), clear(), dequeue(), display(), enqueue(), front(), and isEmpty().
queueSize
int Queue::queueSize private
Definition at line 18 of file queue.h.
Referenced by Queue(), clear(), dequeue(), enqueue(), and size().
rearNode
QueueNode* Queue::rearNode private
Definition at line 17 of file queue.h.
Referenced by Queue(), clear(), dequeue(), and enqueue().
The documentation for this class was generated from the following files:
queue.h
queue.cpp