Structure Simulation: LinkedList Class Reference
LinkedList Class Reference
#include <linked_list.h>
Public Member Functions
LinkedList ()
~LinkedList ()
void clear ()
void deleteAt (int index)
void deleteFirst ()
void deleteLast ()
void display ()
void displayMenu ()
int find (int x)
void handleLinkedListOperations ()
void insertAt (int x, int index)
void insertFirst (int x)
void insertLast (int x)
int size ()
Private Member Functions
ListNode * getNodeAt (int index)
bool isValidIndex (int index)
Private Attributes
ListNode * head
int listSize
Detailed Description
Definition at line 14 of file linked_list.h.
Constructor & Destructor Documentation
LinkedList()
LinkedList::LinkedList ()
Definition at line 5 of file linked_list.cpp.
References head, and listSize.
~LinkedList()
LinkedList::~LinkedList ()
Definition at line 8 of file linked_list.cpp.
References clear().
Member Function Documentation
clear()
void LinkedList::clear ()
Definition at line 164 of file linked_list.cpp.
References head, and listSize.
Referenced by ~LinkedList(), and handleLinkedListOperations().
deleteAt()
void LinkedList::deleteAt (int index)
Definition at line 116 of file linked_list.cpp.
References ListNode::data, deleteFirst(), head, isValidIndex(), listSize, and ListNode::next.
Referenced by handleLinkedListOperations().
deleteFirst()
void LinkedList::deleteFirst ()
Definition at line 40 of file linked_list.cpp.
References head, and listSize.
Referenced by deleteAt(), and handleLinkedListOperations().
deleteLast()
void LinkedList::deleteLast ()
Definition at line 55 of file linked_list.cpp.
References ListNode::data, head, listSize, and ListNode::next.
Referenced by handleLinkedListOperations().
display()
void LinkedList::display ()
Definition at line 175 of file linked_list.cpp.
References ListNode::data, head, and ListNode::next.
Referenced by handleLinkedListOperations().
displayMenu()
void LinkedList::displayMenu ()
Definition at line 216 of file linked_list.cpp.
References CYAN, and RESET.
Referenced by handleLinkedListOperations().
find()
int LinkedList::find (int x)
Definition at line 143 of file linked_list.cpp.
References ListNode::data, head, and ListNode::next.
Referenced by handleLinkedListOperations().
getNodeAt()
ListNode * LinkedList::getNodeAt (int index) private
Definition at line 197 of file linked_list.cpp.
References head, isValidIndex(), and ListNode::next.
handleLinkedListOperations()
void LinkedList::handleLinkedListOperations ()
Definition at line 233 of file linked_list.cpp.
References clear(), cls(), CYAN, deleteAt(), deleteFirst(), deleteLast(), display(), displayMenu(), find(), insertAt(), insertFirst(), insertLast(), listSize, RED, RESET, and size().
Referenced by main().
insertAt()
void LinkedList::insertAt (int x, int index)
Definition at line 85 of file linked_list.cpp.
References head, insertFirst(), insertLast(), listSize, and ListNode::next.
Referenced by handleLinkedListOperations().
insertFirst()
void LinkedList::insertFirst (int x)
Definition at line 13 of file linked_list.cpp.
References head, listSize, and ListNode::next.
Referenced by handleLinkedListOperations(), and insertAt().
insertLast()
void LinkedList::insertLast (int x)
Definition at line 22 of file linked_list.cpp.
References head, listSize, and ListNode::next.
Referenced by handleLinkedListOperations(), and insertAt().
isValidIndex()
bool LinkedList::isValidIndex (int index) private
Definition at line 211 of file linked_list.cpp.
References listSize.
Referenced by deleteAt(), and getNodeAt().
size()
int LinkedList::size ()
Definition at line 159 of file linked_list.cpp.
References listSize.
Referenced by handleLinkedListOperations().
Member Data Documentation
head
ListNode* LinkedList::head private
Definition at line 16 of file linked_list.h.
Referenced by LinkedList(), clear(), deleteAt(), deleteFirst(), deleteLast(), display(), find(), getNodeAt(), insertAt(), insertFirst(), and insertLast().
listSize
int LinkedList::listSize private
Definition at line 17 of file linked_list.h.
Referenced by LinkedList(), clear(), deleteAt(), deleteFirst(), deleteLast(), handleLinkedListOperations(), insertAt(), insertFirst(), insertLast(), isValidIndex(), and size().
The documentation for this class was generated from the following files:
linked_list.h
linked_list.cpp