Structure Simulation: CircularLinkedList Class Reference
CircularLinkedList Class Reference
#include <circular_linked_list.h>
Public Member Functions
CircularLinkedList ()
~CircularLinkedList ()
void clear ()
void deleteAt (int index)
void deleteFirst ()
void deleteLast ()
void display ()
void displayMenu ()
int find (int x)
void handleCircularLinkedListOperations ()
void insertAt (int x, int index)
void insertFirst (int x)
void insertLast (int x)
bool isCircular ()
int size ()
Private Member Functions
CircularListNode * getNodeAt (int index)
bool isValidIndex (int index)
Private Attributes
CircularListNode * head
int listSize
Detailed Description
Definition at line 14 of file circular_linked_list.h.
Constructor & Destructor Documentation
CircularLinkedList()
CircularLinkedList::CircularLinkedList ()
Definition at line 5 of file circular_linked_list.cpp.
References head, and listSize.
~CircularLinkedList()
CircularLinkedList::~CircularLinkedList ()
Definition at line 8 of file circular_linked_list.cpp.
References clear().
Member Function Documentation
clear()
void CircularLinkedList::clear ()
Definition at line 141 of file circular_linked_list.cpp.
References deleteFirst(), and listSize.
Referenced by ~CircularLinkedList(), and handleCircularLinkedListOperations().
deleteAt()
void CircularLinkedList::deleteAt (int index)
Definition at line 107 of file circular_linked_list.cpp.
References CircularListNode::data, deleteFirst(), getNodeAt(), isValidIndex(), listSize, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
deleteFirst()
void CircularLinkedList::deleteFirst ()
Definition at line 46 of file circular_linked_list.cpp.
References head, listSize, and CircularListNode::next.
Referenced by clear(), deleteAt(), and handleCircularLinkedListOperations().
deleteLast()
void CircularLinkedList::deleteLast ()
Definition at line 66 of file circular_linked_list.cpp.
References CircularListNode::data, head, listSize, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
display()
void CircularLinkedList::display ()
Definition at line 155 of file circular_linked_list.cpp.
References CircularListNode::data, head, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
displayMenu()
void CircularLinkedList::displayMenu ()
Definition at line 184 of file circular_linked_list.cpp.
References CYAN, and RESET.
Referenced by handleCircularLinkedListOperations().
find()
int CircularLinkedList::find (int x)
Definition at line 123 of file circular_linked_list.cpp.
References CircularListNode::data, head, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
getNodeAt()
CircularListNode * CircularLinkedList::getNodeAt (int index) private
Definition at line 171 of file circular_linked_list.cpp.
References head, isValidIndex(), and CircularListNode::next.
Referenced by deleteAt(), and insertAt().
handleCircularLinkedListOperations()
void CircularLinkedList::handleCircularLinkedListOperations ()
Definition at line 202 of file circular_linked_list.cpp.
References clear(), cls(), CYAN, deleteAt(), deleteFirst(), deleteLast(), display(), displayMenu(), find(), insertAt(), insertFirst(), insertLast(), isCircular(), listSize, RED, RESET, and size().
Referenced by main().
insertAt()
void CircularLinkedList::insertAt (int x, int index)
Definition at line 90 of file circular_linked_list.cpp.
References getNodeAt(), insertFirst(), insertLast(), listSize, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
insertFirst()
void CircularLinkedList::insertFirst (int x)
Definition at line 13 of file circular_linked_list.cpp.
References head, listSize, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations(), and insertAt().
insertLast()
void CircularLinkedList::insertLast (int x)
Definition at line 30 of file circular_linked_list.cpp.
References head, listSize, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations(), and insertAt().
isCircular()
bool CircularLinkedList::isCircular ()
Definition at line 147 of file circular_linked_list.cpp.
References head, and CircularListNode::next.
Referenced by handleCircularLinkedListOperations().
isValidIndex()
bool CircularLinkedList::isValidIndex (int index) private
Definition at line 179 of file circular_linked_list.cpp.
References listSize.
Referenced by deleteAt(), and getNodeAt().
size()
int CircularLinkedList::size ()
Definition at line 136 of file circular_linked_list.cpp.
References listSize.
Referenced by handleCircularLinkedListOperations().
Member Data Documentation
head
CircularListNode* CircularLinkedList::head private
Definition at line 16 of file circular_linked_list.h.
Referenced by CircularLinkedList(), deleteFirst(), deleteLast(), display(), find(), getNodeAt(), insertFirst(), insertLast(), and isCircular().
listSize
int CircularLinkedList::listSize private
Definition at line 17 of file circular_linked_list.h.
Referenced by CircularLinkedList(), clear(), deleteAt(), deleteFirst(), deleteLast(), handleCircularLinkedListOperations(), insertAt(), insertFirst(), insertLast(), isValidIndex(), and size().
The documentation for this class was generated from the following files:
circular_linked_list.h
circular_linked_list.cpp